name: Build and deploy Python API to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install PyTorch explicitly
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.0.1 --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Create deployment artifact
        run: |
          pip install -r api/requirements.txt
          cd api
          echo '#!/bin/bash' > install_torch.sh
          echo 'pip install torch==2.0.1 --extra-index-url https://download.pytorch.org/whl/cpu' >> install_torch.sh
          chmod +x install_torch.sh
          cd ..
          zip -r release.zip api
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_781F2029FCF242A7A8F90200DD2EE175 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6DF935C353A14A43BBF4D93BEA39E929 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_88F11AB3B70244838BBB370BF3B6CDEE }}
      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: tomgorbett-api
          slot-name: Production
          package: release.zip
          clean: true
          startup-command: |
            cd api && ./install_torch.sh && cd .. && gunicorn -w 4 -b 0.0.0.0:$PORT api:app
